services:
  frontend:
    build:
      context: ./frontend
      target: dev
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - NEXT_PUBLIC_SUPABASE_URL=https://avcehoxfcyqjllctwjzd.supabase.co
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF2Y2Vob3hmY3lxamxsY3R3anpkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0NDk5OTksImexCI6MjA3MjAyNTk5OX0.quDmqW9YoYM0F0EV6A6a6VNkr7m1ij7t4CI2Bgoe6FM
    depends_on:
      - api
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: npm run dev
    profiles: ["dev"]

  frontend-prod:
    build:
      context: ./frontend
      target: runner
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://api:8000
      - NEXT_PUBLIC_SUPABASE_URL=https://avcehoxfcyqjllctwjzd.supabase.co
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI0ImF2Y2Vob3hmY3lxamllsY3R3anpkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0NDk5OTksImV4cCI6MjA3MjAyNTk5OX00.quDmqW9YoYM0F0EV6A6a6VNkr7m1ij7t7CI2Bgoe6FM
      - NODE_ENV=production
    depends_on:
      - api
    profiles: ["production"]

  api:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/zidisha_db
      - REDIS_URL=redis://redis:6379
      - CORS_ORIGINS=http://localhost:3000,http://frontend:3000,http://localhost:3001,http://localhost:3002,http://localhost:5173
      - PYTHONPATH=/app
      - ENVIRONMENT=development
    depends_on:
      - db
      - redis
    volumes:
      - ./backend:/app
    command: uvicorn main:app --host 0.0.0.0 --reload
    profiles: ["dev"]

  api-prod:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/zidisha_db
      - REDIS_URL=redis://redis:6379
      - CORS_ORIGINS=http://frontend-prod:3000,http://localhost:3001,http://localhost:3002
      - PYTHONPATH=/app
      - ENVIRONMENT=production
      - PORT=8000 # Added default port to silence warning
    depends_on:
      - db
      - redis
    command: gunicorn -k uvicorn.workers.UvicornWorker -b 0.0.0.0:$PORT main:app
    profiles: ["production"]

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=zidisha_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend-prod
      - api-prod
    profiles: ["production"]

  test: # New service for running backend tests
    build: ./backend # Build from the backend Dockerfile
    environment:
      # Override DATABASE_URL for tests to use a separate test database
      - DATABASE_URL=postgresql+asyncpg://postgres:password@db:5432/test_db
      - REDIS_URL=redis://redis:6379
      - PYTHONPATH=/app # Ensure Python can find app modules
      - DEBUG=True # Enable debug mode for tests
      - SECRET_KEY=test-secret-key # Required for auth tests
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - CORS_ORIGINS=http://localhost:3000
      - AFRICAS_TALKING_API_KEY=mock_key
      - AFRICAS_TALKING_USERNAME=mock_user
      - SMS_SENDER_ID=LOYALTY
      - DARAJA_API_URL=https://sandbox.safaricom.co.ke
      - DARAAA_API_KEY=mock_daraja_key
    depends_on:
      db:
        condition: service_healthy # Ensure DB is healthy before running tests
      redis:
        condition: service_healthy # Ensure Redis is healthy before running tests
    volumes:
      - ./backend:/app
    command: /bin/bash -c "pytest tests/" # Command to run pytest
    healthcheck: # Health checks for db and redis are already defined in their services
      test: ["CMD-SHELL", "pg_isready -U postgres -h db"]
      interval: 5s
      timeout: 5s
      retries: 5
    profiles: ["test"] # Only run this service when 'test' profile is active

volumes:
  postgres_data:

networks:
  default:
    name: zidisha-network