services:
  frontend:
    build:
      context: ./frontend # Updated context to frontend directory
      target: base
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - NEXT_PUBLIC_SUPABASE_URL=https://avcehoxfcyqjllctwjzd.supabase.co
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF2Y2Vob3hmY3lxamxsY3R3anpkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0NDk5OTksImV4cCI6MjA3MjAyNTk5OX0.quDmqW9YoYM0F0EV6A6a6VNkr7m1ij7t4CI2Bgoe6FM
    depends_on:
      - api
    volumes:
      - ./frontend:/app # Updated volume mount to frontend directory
    working_dir: /app
    command: npm run dev
    profiles: ["dev"]

  frontend-prod:
    build:
      context: ./frontend # Updated context to frontend directory
      target: runner
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://api:8000
      - NEXT_PUBLIC_SUPABASE_URL=https://avcehoxfcyqjllctwjzd.supabase.co
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI0ImF2Y2Vob3hmY3lxamllsY3R3anpkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0NDk5OTksImV4cCI6MjA3MjAyNTk5OX0.quDmqW9YoYM0F0EV6A6a6VNkr7m1ij7t7CI2Bgoe6FM
      - NODE_ENV=production
    depends_on:
      - api
    profiles: ["production"]

  api:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/zidisha_db
      - REDIS_URL=redis://redis:6379
      - CORS_ORIGINS=http://localhost:3000,http://frontend:3000,http://localhost:3001,http://localhost:3002,http://localhost:5173 # Added localhost:5173 for Vite dev server
      - PYTHONPATH=/app
      - ENVIRONMENT=development # Added for local development
    depends_on:
      - db
      - redis
    volumes:
      - ./backend:/app
    command: uvicorn main:app --host 0.0.0.0 --reload # Removed hardcoded port
    profiles: ["dev"]

  api-prod:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/zidisha_db
      - REDIS_URL=redis://redis:6379
      - CORS_ORIGINS=http://frontend-prod:3000,http://localhost:3001,http://localhost:3002 # This should be the actual production frontend URL
      - PYTHONPATH=/app
      - ENVIRONMENT=production # Added for production
    depends_on:
      - db
      - redis
    command: gunicorn -k uvicorn.workers.UvicornWorker -b 0.0.0.0:$PORT main:app # Used $PORT environment variable
    profiles: ["production"]

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=zidisha_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend-prod
      - api-prod
    profiles: ["production"]

volumes:
  postgres_data:

networks:
  default:
    name: zidisha-network